import '../models/coverage_report.dart';
import '../models/template_cluster.dart';

/// Renders a [CoverageReport] into a developer-facing Markdown document:
/// overall coverage, a per-parser health dashboard, and a prioritized list of
/// unmatched template clusters.
class MarkdownReport {
  final CoverageReport report;
  final String parserName;
  final int topClusters;

  const MarkdownReport(
    this.report, {
    this.parserName = 'Parser',
    this.topClusters = 25,
  });

  String render() {
    final b = StringBuffer();
    _header(b);
    _summary(b);
    _parserDashboard(b);
    _unmatchedClusters(b);
    _footer(b);
    return b.toString();
  }

  void _header(StringBuffer b) {
    b.writeln('# SMS Pattern Lab — Coverage Report');
    b.writeln();
    b.writeln('_Parser framework: **$parserName**_');
    b.writeln();
  }

  void _summary(StringBuffer b) {
    b.writeln('## Summary');
    b.writeln();
    b.writeln('| Metric | Value |');
    b.writeln('|---|---|');
    b.writeln('| Total messages | ${report.total} |');
    b.writeln('| Matched | ${report.matched} |');
    b.writeln('| Unmatched | ${report.unmatched} |');
    b.writeln('| Unattributed (no bank) | ${report.unattributed} |');
    b.writeln(
        '| **Overall coverage** | **${_pct(report.overallCoveragePercent)}** |');
    b.writeln('| Distinct unmatched templates | '
        '${report.unmatchedClusters.length} |');
    b.writeln();
  }

  void _parserDashboard(StringBuffer b) {
    b.writeln('## Parser Health Dashboard');
    b.writeln();
    if (report.parsers.isEmpty) {
      b.writeln('_No attributable messages in dataset._');
      b.writeln();
      return;
    }

    b.writeln('| Parser | Coverage | Matched | Unmatched | Total |');
    b.writeln('|---|---:|---:|---:|---:|');
    for (final p in report.parsers) {
      b.writeln('| ${p.bankName} | ${_pct(p.coveragePercent)} | '
          '${p.matched} | ${p.unmatched} | ${p.total} |');
    }
    b.writeln();

    // Per-parser detail with the single biggest missing template.
    for (final p in report.parsers) {
      if (p.unmatched == 0) continue;
      b.writeln('### ${p.bankName}');
      b.writeln();
      b.writeln('- **Coverage:** ${_pct(p.coveragePercent)}');
      final largest = p.largestMissingTemplate;
      if (largest != null) {
        b.writeln('- **Largest missing template:** '
            '`${_inline(largest.template)}`');
        b.writeln('- **Occurrences:** ${largest.occurrences}');
        b.writeln('- **Priority:** ${largest.priority}');
      }
      b.writeln();
    }
  }

  void _unmatchedClusters(StringBuffer b) {
    b.writeln('## Unmatched Pattern Reports');
    b.writeln();
    final clusters = report.unmatchedClusters;
    if (clusters.isEmpty) {
      b.writeln('🎉 No unmatched messages — every parser is fully covered for '
          'this dataset.');
      b.writeln();
      return;
    }

    final shown = clusters.take(topClusters).toList();
    if (clusters.length > shown.length) {
      b.writeln('_Showing top ${shown.length} of ${clusters.length} '
          'unmatched template clusters (ranked by priority)._');
      b.writeln();
    }

    var i = 1;
    for (final c in shown) {
      _cluster(b, i++, c);
    }
  }

  void _cluster(StringBuffer b, int index, TemplateCluster c) {
    b.writeln('### $index. ${c.priority} — ${c.occurrences} occurrence'
        '${c.occurrences == 1 ? '' : 's'}');
    b.writeln();
    b.writeln('- **Likely parser:** ${c.likelyBankName ?? 'Unknown'}');
    if (c.similarityGroup != null) {
      b.writeln('- **Similarity group:** ${c.similarityGroup}');
    }
    b.writeln('- **Template:** `${_inline(c.template)}`');
    if (c.examples.isNotEmpty) {
      b.writeln('- **Examples:**');
      for (final ex in c.examples) {
        b.writeln('  - `${_inline(ex)}`');
      }
    }
    b.writeln();
  }

  void _footer(StringBuffer b) {
    b.writeln('---');
    b.writeln();
    b.writeln('_Generated by SMS Pattern Lab — a standalone parser diagnostics '
        'and pattern discovery tool. No production code was modified._');
  }

  String _pct(double v) => '${v.toStringAsFixed(1)}%';

  /// Make a string safe for an inline code span (strip backticks/newlines).
  String _inline(String s) =>
      s.replaceAll('`', '‘').replaceAll(RegExp(r'\s+'), ' ').trim();
}
